### ISSUE TITLE
Keyboard control does not die on Ctrl+C

### ISSUE THREAD

**Issue by AlfaKeNTAvR** [GOPHER-System-Intergration/gopher-keyboard-control#1]
while not rospy.is_shutdown():
        try:
            computer_keyboard.keys_map_robot_control(keys = current_keys)
        
        # kills the thread once we choose to shut down ros operations
        except:
            listener.join()

    listener.join()

**Comment by iceikking888** [comment]
realized I had the wrong command. Instead of using listener.join, it should be listener.stop()
